apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-chart
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: dummy-chart
  template:
    metadata:
      labels:
        app: dummy-chart
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
